### PR TITLE
Updates for pr

### PR DESCRIPTION
**Pull request by smartiniOnGitHub**
Hi, in this PR I updated all dependencies to latest, and add some minimal tests using Tap (node-tap).
Updated source code to be more compliant with latest JavaScript syntax.

Note that some unit tests are by default disabled because to test even local ssh connections some local setup, so I used some environmment variables to enable and configure those details; I'm thinking now to add even 'dotenv' to dev dependencies to simplify env vars setup (with ignored .env file).
For more tests, I have others running an ssh server in a Docker container (at the moment only in another branch in my fork) which works but I need to integrate with current tests; not sure you are interested in these tests (and still I'm improving for example the current container based on ubuntu works, but not the one based on alpine), and ssh connections works with the key (I need to enable even ssh login with password, to enable other tests); anyway all this part is in a folder and some npm custom command to put in 'package.json'. Tell me if you think this part would be useful too.

Hope proposed changes are good, otherwise tell me.

In the 'package.json' I set an arbitrary release to '2.5.0', hope is good too.

Tell me what you think.

Thans for now,
Sandro

### CODE REVIEW

**Comment by smartiniOnGitHub** [comment]
With latest updates it's simpler to parametrize unit tests ... Bye

**Comment by bitsinside** [comment]
@smartiniOnGitHub how to run that libray if i want to modify some codes.

**Comment by smartiniOnGitHub** [comment]
Hi and thanks for the reply.
In another branch in my fork I have other stuff to test ssh connections to a target ssh server exposed via a Docker container, you can find it [here](https://github.com/smartiniOnGitHub/ssh-exec/tree/update-dependencies-and-syntax), hope you like it (it need Docker installed but otherwise it would be hard to test in a general way).
After so much time I can update dependencies in both branches (and update this PR), so see PR as step 1; then raise another PR for the tests via container if you like it (otherwise do all in this PR), as you prefer. Tell me. Thanks for now.

**Comment by smartiniOnGitHub** [comment]
I just update dependencies to latest and update code to pass lint phase now (still don't see today commit here, I need to check); to test ssh connection you need to run tests with an env var flag enabled, like:
```
SSH_LOCALHOST_USERKEY_ENABLE_TEST=true npm run test
```
and you need to define env vars for connection credentials: SSH_HOST, SSH_PORT, SSH_USER, SSH_PASS, SSH_KEY
The reason to have 'dotenv' in dev dependencies here now is because you can set all them in a file '.env' and be loaded in automatic way by test sources.

Instead, to test all in isolation, in my other branch (related code not in this PR, but if you want I can add too here) I setup an ssh server using a Docker container, so that all can be done locally without tricks; just for info it's here:
https://github.com/smartiniOnGitHub/ssh-exec/tree/update-dependencies-and-syntax/docker

Just redo all tests (with an ssh server running in a container) and ssh connection works.

Tell me what you think.
Thanks a lot.

**Comment by smartiniOnGitHub** [comment]
Sorry still (even after a rebase and force push) I don't see updated content in this PR; I'll close now and open an new one ...

**Pull request closed without merging**
